# Generated by Django 5.2.13 on 2026-06-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='user_id',
            field=models.PositiveBigIntegerField(db_index=True),
        ),
    ]
