# Generated by Django 5.2 on 2026-04-14

from django.db import migrations, models
from pgvector.django import VectorField


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0002_pgvector_and_documents"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductEmbedding",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("product_id", models.PositiveBigIntegerField(db_index=True, unique=True)),
                ("embedding", VectorField(dimensions=64)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserEmbedding",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("user_id", models.CharField(db_index=True, max_length=64, unique=True)),
                ("embedding", VectorField(dimensions=64)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]

