# Generated by Django 5.2 on 2026-04-26

from django.db import migrations, models
from pgvector.django import VectorField


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0005_pgvector_hnsw_indexes"),
    ]

    operations = [
        migrations.CreateModel(
            name="GnnProductEmbedding",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("product_id", models.PositiveBigIntegerField(db_index=True, unique=True)),
                ("embedding", VectorField(dimensions=64)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="GnnUserEmbedding",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("user_id", models.CharField(db_index=True, max_length=64, unique=True)),
                ("embedding", VectorField(dimensions=64)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RunSQL(
            sql="""
            CREATE INDEX IF NOT EXISTS ai_gnnproductembedding_embedding_hnsw_cosine
            ON ai_gnnproductembedding
            USING hnsw (embedding vector_cosine_ops)
            WITH (m = 16, ef_construction = 64);
            """,
            reverse_sql="DROP INDEX IF EXISTS ai_gnnproductembedding_embedding_hnsw_cosine;",
        ),
    ]

