# Generated by Django 5.2.13 on 2026-06-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0007_chatturn_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatturn',
            name='user_id',
            field=models.PositiveBigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='gnnuserembedding',
            name='user_id',
            field=models.PositiveBigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='userembedding',
            name='user_id',
            field=models.PositiveBigIntegerField(unique=True),
        ),
    ]
