# Generated by Django 5.2 on 2026-04-13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("user_id", models.CharField(db_index=True, max_length=64)),
                ("session_id", models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ("event_type", models.CharField(db_index=True, max_length=64)),
                ("product_id", models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ("query", models.TextField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]

