# Generated by Django 5.2.10 on 2026-04-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='initial_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
