# Generated by Django 5.2 on 2026-04-26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_status",
            field=models.CharField(default="PENDING", max_length=32),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_id",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_status",
            field=models.CharField(default="PENDING", max_length=32),
        ),
        migrations.AddField(
            model_name="order",
            name="shipment_id",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="tracking_code",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]

