# Generated by Django 5.2.13 on 2026-06-08 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_inventory_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipment_id',
        ),
    ]
