# Generated by Django 5.2.13 on 2026-06-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_payment_id_remove_order_shipment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user_id',
            field=models.PositiveBigIntegerField(db_index=True),
        ),
    ]
