# Generated by Django 5.2 on 2026-04-26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Shipment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("user_id", models.CharField(max_length=64)),
                ("order_id", models.PositiveBigIntegerField(db_index=True)),
                ("status", models.CharField(default="CREATED", max_length=32)),
                ("carrier", models.CharField(default="mock", max_length=32)),
                ("tracking_code", models.CharField(db_index=True, max_length=64)),
                ("address", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["-created_at"]},
        ),
    ]

