# Generated by Django 5.1.6 on 2026-06-09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_product_image_alter_product_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="tag",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="product",
            name="actual_price",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="link",
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="main_category",
            field=models.CharField(
                choices=[("BOOK", "Book"), ("ELECTRONICS", "Electronics"), ("FASHION", "Fashion")],
                default="ELECTRONICS",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="no_of_ratings",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="ratings",
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("author", models.CharField(blank=True, default="", max_length=255)),
                ("publisher", models.CharField(blank=True, default="", max_length=255)),
                ("isbn", models.CharField(blank=True, default="", max_length=32)),
                ("language", models.CharField(blank=True, default="", max_length=64)),
                (
                    "product",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="book", to="catalog.product"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Electronics",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("brand", models.CharField(blank=True, default="", max_length=120)),
                ("color", models.CharField(blank=True, default="", max_length=64)),
                ("warranty_months", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "product",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="electronics", to="catalog.product"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Fashion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("size", models.CharField(blank=True, default="", max_length=32)),
                ("color", models.CharField(blank=True, default="", max_length=64)),
                ("gender", models.CharField(blank=True, default="", max_length=32)),
                ("brand", models.CharField(blank=True, default="", max_length=120)),
                (
                    "product",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="fashion", to="catalog.product"),
                ),
            ],
        ),
    ]
