# Generated by Django 5.1.6 on 2026-06-09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_book_electronics_fashion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="actual_price",
        ),
        migrations.RemoveField(
            model_name="product",
            name="link",
        ),
    ]
