# Generated by Cursor on 2026-04-27

from django.db import migrations, models


def seed_roles(apps, schema_editor):
    Role = apps.get_model("users", "Role")
    Customer = apps.get_model("users", "Customer")

    customer_role, _ = Role.objects.get_or_create(name="customer", defaults={"description": "Default customer role"})
    Role.objects.get_or_create(name="staff", defaults={"description": "Staff role"})
    Role.objects.get_or_create(name="admin", defaults={"description": "Admin role"})

    # Backfill existing customers
    Customer.objects.filter(role__isnull=True).update(role=customer_role)


def unseed_roles(apps, schema_editor):
    Role = apps.get_model("users", "Role")
    # Best-effort rollback
    Role.objects.filter(name__in=["customer", "staff", "admin"]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=64, unique=True)),
                ("description", models.CharField(blank=True, default="", max_length=255)),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="customer",
            name="role",
            field=models.ForeignKey(blank=True, null=True, on_delete=models.deletion.PROTECT, related_name="customers", to="users.role"),
        ),
        migrations.RunPython(seed_roles, unseed_roles),
    ]

