# Generated by Django 5.2.13 on 2026-06-08 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_delete_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
    ]
